#!/bin/bash

# Ejecutar como super usuario
# Desde la carpeta tanalizer
# chmod +x install_project
# sudo ./install_project

touch mastertopics.txt
touch settings_local.py

apt-get install mysql-server python-django python-mysqldb python-beautifulsoup python-numpy python2.7-dev apparmor-utils libapache2-mod-wsgi

wget https://github.com/downloads/jorgebastida/django-dajaxice/django-dajaxice-0.2.tar.gz

tar -zxvf django-dajaxice-0.2.tar.gz
rm django-dajaxice-0.2.tar.gz
cd django-dajaxice-0.2
python setup.py install
cd ..
rm -fr django-dajaxice-0.2

wget https://github.com/downloads/jorgebastida/django-dajax/django-dajax-0.8.4.tar.gz

tar -zxvf django-dajax-0.8.4.tar.gz
rm django-dajax-0.8.4.tar.gz
cd django-dajax-0.8.4
python setup.py install
cd ..
rm -fr django-dajax-0.8.4

wget http://pages.cs.wisc.edu/~andrzeje/research/deltaLDA.tgz

tar -zxvf deltaLDA.tgz
rm deltaLDA.tgz
cd deltaLDA-0.1.1
python setup.py install
cd ..
rm -fr deltaLDA-0.1.1

apt-get install libpcre3-dev libdb4.7++-dev libboost-dev
apt-get install libboost1.40-dev

apt-get install libboost-filesystem-dev libboost-program-options-dev
apt-get install libboost-regex-dev libicu-dev

sudo ln -s /usr/include/boost/property_map/property_map.hpp /user/include/boost/property_map.hpp

PROJECT_DIR=`pwd`

wget http://devel.cpl.upc.edu/freeling/downloads/14 -O libfries-1.2.1.tar.gz
tar xvf libfries-1.2.1.tar.gz
rm libfries-1.2.1.tar.gz
cd libfries-1.2.1
./configure --prefix=$PROJECT_DIR/stemmer
make && make install
cd ..
rm -fr libfries-1.2.1

wget http://devel.cpl.upc.edu/freeling/downloads/7 -O libomlet-1.0.1.tar.gz
tar xvf libomlet-1.0.1.tar.gz
rm libomlet-1.0.1.tar.gz
cd libomlet-1.0.1
./configure --prefix=$PROJECT_DIR/stemmer
make && make install
cd ..
rm -fr libomlet-1.0.1

wget http://devel.cpl.upc.edu/freeling/downloads/15 -O FreeLing-2.2.2.tar.gz
tar xvf FreeLing-2.2.2.tar.gz
rm FreeLing-2.2.2.tar.gz
cd FreeLing-2.2.2
./configure CPPFLAGS=-I$PROJECT_DIR/stemmer/include LDFLAGS=-L$PROJECT_DIR/stemmer/lib --prefix=$PROJECT_DIR/stemmer
make && make install
cd ..
rm -fr FreeLing-2.2.2
